### ISSUE TITLE
 how to start cheat?

### ISSUE THREAD

**Issue by krazelox** [AquaDev86/AqHax-CSGO#2]
how to start cheat?

**Comment by krxdev-kaan** [comment]
Currently WIP but there isn’t much left to do so this hack will be in works in just a while. Thanks for checking out 👍.

**Comment by krxdev-kaan** [comment]
You can start it by just opening the project in Visual Studio and launching it like you normally would but a exe realease is coming soon and thats what i recommend doing :) (Finally back to game hacking and everything will be finished very soon)

Additional Note: You can get an error about a CSG.dat file just comment out the lines that causing the error.
