### ISSUE TITLE
Knife bug

### ISSUE THREAD

**Issue by BurakBalamir** [AquaDev86/AqHax-CSGO#6]
just working bayonet. can't change knife.

**Comment by krxdev-kaan** [comment]
that's pretty weird. it's working for me ? lemme check if the release that i put is broken.

**Comment by krxdev-kaan** [comment]
Verified. Somehow the release is broken. New release on the way in 5 minutes !

**Comment by krxdev-kaan** [comment]
Released. Waiting for your approval to close this issue 👍

**Comment by BurakBalamir** [comment]
fixed issue 👍

**Comment by krxdev-kaan** [comment]
Thanks for approval, closing the issue 👍
