### ISSUE TITLE
Knife Changer makes hands go invisible

### ISSUE THREAD

**Issue by gahdamnfr** [AquaDev86/AqHax-CSGO#9]
When enabling knife changer my model hands go invisible and there is no knife to be seen but if i go into third person I can see that my character has the selected changed knife in his back, can you fix this?

**Comment by krxdev-kaan** [comment]
Hi, finally got back to this project. Today i tested the hack for 2 hours straight but I couldn't recreate the issue. Could you provide more info ? perhaps the problem gone away mystically ?

**Comment by krxdev-kaan** [comment]
Assuming the issue gone away mystically. If not, feel free to reopen the issue.
